### ISSUE TITLE
Commits pushing

### ISSUE THREAD

**Issue by lecriste** [lecriste/Z4430_AAFit#1]
Hi Adriano,
please push a commit only when you are fine with your updates and use a meaningful description message. Try to avoid single line commits because they make the review of the code more difficult.

I noticed that you pushed commits with two different usernames ("AdrianoDee" and "adrianodif"), do you know why it happens?

Cheers

**Comment by AdrianoDee** [comment]
Hi Leo,

sorry! I'll tidy up my commits and I'll do my tests offline. I don't know why my commits appears with two different usernames but It seems that it depends on me pushing from my laptop or from the HPC cluster. By now I'll push only from my laptop to keep always the same username (AdrianoDee).

Cheers!

**Comment by lecriste** [comment]
I think you can keep pushing from multiple devices, you just need to set
the same Git username in all of them.

Leo
